//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoThanks.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoThanks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña Actual.
        /// </summary>
        public static string CHANGEPASSWORD_ACTUALPASSWORD_LABEL {
            get {
                return ResourceManager.GetString("CHANGEPASSWORD_ACTUALPASSWORD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Nueva Contraseña.
        /// </summary>
        public static string CHANGEPASSWORD_COMFIRMPASSWORD_LABEL {
            get {
                return ResourceManager.GetString("CHANGEPASSWORD_COMFIRMPASSWORD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Contraseña.
        /// </summary>
        public static string CHANGEPASSWORD_NEWPASSWORD_LABEL {
            get {
                return ResourceManager.GetString("CHANGEPASSWORD_NEWPASSWORD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Thanks: el Juego – Cambiar Contraseña.
        /// </summary>
        public static string CHANGEPASSWORD_TITLE_WINDOW {
            get {
                return ResourceManager.GetString("CHANGEPASSWORD_TITLE-WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Token.
        /// </summary>
        public static string CHANGEPASSWORD_TOKEN_LABEL {
            get {
                return ResourceManager.GetString("CHANGEPASSWORD_TOKEN_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string CHAT_SEND_BUTTON {
            get {
                return ResourceManager.GetString("CHAT_SEND_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat.
        /// </summary>
        public static string CHAT_TITLE_WINDOW {
            get {
                return ResourceManager.GetString("CHAT_TITLE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AFK.
        /// </summary>
        public static string EXPEL_REASONAFK_CHECKBOX {
            get {
                return ResourceManager.GetString("EXPEL_REASONAFK_CHECKBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trampas.
        /// </summary>
        public static string EXPEL_REASONCHEAT_CHECKBOX {
            get {
                return ResourceManager.GetString("EXPEL_REASONCHEAT_CHECKBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuerda mantener un comportamiento sano para no arruinar la experiencia de juego de los demás.
        /// </summary>
        public static string EXPEL_REASONMESSAGE_CHECKBOX {
            get {
                return ResourceManager.GetString("EXPEL_REASONMESSAGE_CHECKBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comportamiento Toxico.
        /// </summary>
        public static string EXPEL_REASONTOXIC_CHECKBOK {
            get {
                return ResourceManager.GetString("EXPEL_REASONTOXIC_CHECKBOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motivo de la Expulsión.
        /// </summary>
        public static string EXPEL_TITLE_LABEL {
            get {
                return ResourceManager.GetString("EXPEL_TITLE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expulsar Jugador.
        /// </summary>
        public static string EXPEL_TITLE_WINDOW {
            get {
                return ResourceManager.GetString("EXPEL_TITLE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        public static string GENERAL_BACK_BUTTON {
            get {
                return ResourceManager.GetString("GENERAL_BACK_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string GENERAL_CANCEL_BUTTON {
            get {
                return ResourceManager.GetString("GENERAL_CANCEL_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        public static string GENERAL_CONFIRM_BUTTON {
            get {
                return ResourceManager.GetString("GENERAL_CONFIRM_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        public static string GENERAL_NEXT_BUTTON {
            get {
                return ResourceManager.GetString("GENERAL_NEXT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string JOINGAME_GAMECODE_LABEL {
            get {
                return ResourceManager.GetString("JOINGAME_GAMECODE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse.
        /// </summary>
        public static string JOINGAME_JOIN_BUTTON {
            get {
                return ResourceManager.GetString("JOINGAME_JOIN_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a Partida (con Código).
        /// </summary>
        public static string JOINGAME_TITLE_WINDOW {
            get {
                return ResourceManager.GetString("JOINGAME_TITLE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string LANGUAGE_ENGLISH_COLUMN {
            get {
                return ResourceManager.GetString("LANGUAGE_ENGLISH_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        public static string LANGUAGE_SELECT_BUTTON {
            get {
                return ResourceManager.GetString("LANGUAGE_SELECT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string LANGUAGE_SPANISH_COLUMN {
            get {
                return ResourceManager.GetString("LANGUAGE_SPANISH_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lenguaje.
        /// </summary>
        public static string LANGUAGE_TITLE_TABLE {
            get {
                return ResourceManager.GetString("LANGUAGE_TITLE_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar como Invitado.
        /// </summary>
        public static string LOGIN_GUEST_LABEL {
            get {
                return ResourceManager.GetString("LOGIN_GUEST_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        public static string LOGIN_LOGIN_BUTTON {
            get {
                return ResourceManager.GetString("LOGIN_LOGIN_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de Sesión.
        /// </summary>
        public static string LOGIN_LOGINTITLE_LABEL {
            get {
                return ResourceManager.GetString("LOGIN_LOGINTITLE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string LOGIN_PASSWORD_LABEL {
            get {
                return ResourceManager.GetString("LOGIN_PASSWORD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string LOGIN_REGISTER_BUTTON {
            get {
                return ResourceManager.GetString("LOGIN_REGISTER_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Thanks: El Juego.
        /// </summary>
        public static string LOGIN_TITLE_WINDOW {
            get {
                return ResourceManager.GetString("LOGIN_TITLE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Usuario.
        /// </summary>
        public static string LOGIN_USERNAME_LABEL {
            get {
                return ResourceManager.GetString("LOGIN_USERNAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Thanks: Menu Principal.
        /// </summary>
        public static string MAINMENU_TITLE_WINDOW {
            get {
                return ResourceManager.GetString("MAINMENU_TITLE-WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalizacion.
        /// </summary>
        public static string PERSONALIZATION_BUTTON {
            get {
                return ResourceManager.GetString("PERSONALIZATION_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Thanks: Personalizacion.
        /// </summary>
        public static string PERSONALIZATION_TITLE_WINDOW {
            get {
                return ResourceManager.GetString("PERSONALIZATION_TITLE-WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar.
        /// </summary>
        public static string PLAY_BUTTON {
            get {
                return ResourceManager.GetString("PLAY_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Thanks: Perfil.
        /// </summary>
        public static string PROFILE_TITLE_WINDOW {
            get {
                return ResourceManager.GetString("PROFILE_TITLE-WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del jugador.
        /// </summary>
        public static string RESULT_PLAYERNAME_LABEL {
            get {
                return ResourceManager.GetString("RESULT_PLAYERNAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a puntos.
        /// </summary>
        public static string RESULT_SCOREUNIT_LABEL {
            get {
                return ResourceManager.GetString("RESULT_SCOREUNIT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultados.
        /// </summary>
        public static string RESULT_TITLE_WINDOW {
            get {
                return ResourceManager.GetString("RESULT_TITLE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ganador.
        /// </summary>
        public static string RESULT_WINNER_LABEL {
            get {
                return ResourceManager.GetString("RESULT_WINNER_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tú.
        /// </summary>
        public static string RESULT_YOU_LABEL {
            get {
                return ResourceManager.GetString("RESULT_YOU_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pasar.
        /// </summary>
        public static string ROOM_PASS_BUTTON {
            get {
                return ResourceManager.GetString("ROOM_PASS_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Partida.
        /// </summary>
        public static string ROOM_STARTGAME_BUTTON {
            get {
                return ResourceManager.GetString("ROOM_STARTGAME_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tomar.
        /// </summary>
        public static string ROOM_TAKE_BUTTON {
            get {
                return ResourceManager.GetString("ROOM_TAKE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala.
        /// </summary>
        public static string ROOM_TITLE_WINDOW {
            get {
                return ResourceManager.GetString("ROOM_TITLE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperando a que el anfitrión comience la partida….
        /// </summary>
        public static string ROOM_WAITING_MESSAGE {
            get {
                return ResourceManager.GetString("ROOM_WAITING_MESSAGE", resourceCulture);
            }
        }
    }
}
