//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoThanks.NoThanksService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/Logic")]
    [System.SerializableAttribute()]
    public partial class Player : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NoThanks.NoThanksService.CardType[] CardsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardsStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPlayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfileImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TokensField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TotalScoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NoThanks.NoThanksService.CardType[] Cards {
            get {
                return this.CardsField;
            }
            set {
                if ((object.ReferenceEquals(this.CardsField, value) != true)) {
                    this.CardsField = value;
                    this.RaisePropertyChanged("Cards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardsString {
            get {
                return this.CardsStringField;
            }
            set {
                if ((object.ReferenceEquals(this.CardsStringField, value) != true)) {
                    this.CardsStringField = value;
                    this.RaisePropertyChanged("CardsString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPlayer {
            get {
                return this.IdPlayerField;
            }
            set {
                if ((this.IdPlayerField.Equals(value) != true)) {
                    this.IdPlayerField = value;
                    this.RaisePropertyChanged("IdPlayer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfileImage {
            get {
                return this.ProfileImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileImageField, value) != true)) {
                    this.ProfileImageField = value;
                    this.RaisePropertyChanged("ProfileImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tokens {
            get {
                return this.TokensField;
            }
            set {
                if ((this.TokensField.Equals(value) != true)) {
                    this.TokensField = value;
                    this.RaisePropertyChanged("Tokens");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TotalScore {
            get {
                return this.TotalScoreField;
            }
            set {
                if ((this.TotalScoreField.Equals(value) != true)) {
                    this.TotalScoreField = value;
                    this.RaisePropertyChanged("TotalScore");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardType", Namespace="http://schemas.datacontract.org/2004/07/Logic")]
    public enum CardType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Three = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Four = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Five = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Six = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Seven = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Eight = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nine = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ten = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Eleven = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Twelve = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Thirteen = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fourteen = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fifteen = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sixteen = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Seventeen = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Eightteen = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nineteen = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Twenty = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TwentyOne = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TwentyTwo = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TwentyThree = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TwentyFour = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TwentyFive = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TwentySix = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TwentySeven = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TwentyEight = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TwentyNine = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Thirty = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ThirtyOne = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ThirtyTwo = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ThirtyThree = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ThirtyFour = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ThirtyFive = 35,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomStatus", Namespace="http://schemas.datacontract.org/2004/07/Logic")]
    public enum RoomStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Waitting = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Started = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Finished = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NoThanksService.IPlayerManager")]
    public interface IPlayerManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/Login", ReplyAction="http://tempuri.org/IPlayerManager/LoginResponse")]
        NoThanks.NoThanksService.Player Login(string nickname, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/Login", ReplyAction="http://tempuri.org/IPlayerManager/LoginResponse")]
        System.Threading.Tasks.Task<NoThanks.NoThanksService.Player> LoginAsync(string nickname, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/Register", ReplyAction="http://tempuri.org/IPlayerManager/RegisterResponse")]
        bool Register(NoThanks.NoThanksService.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/Register", ReplyAction="http://tempuri.org/IPlayerManager/RegisterResponse")]
        System.Threading.Tasks.Task<bool> RegisterAsync(NoThanks.NoThanksService.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/GenerateCode", ReplyAction="http://tempuri.org/IPlayerManager/GenerateCodeResponse")]
        int GenerateCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/GenerateCode", ReplyAction="http://tempuri.org/IPlayerManager/GenerateCodeResponse")]
        System.Threading.Tasks.Task<int> GenerateCodeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/ExistsEmailOrNickname", ReplyAction="http://tempuri.org/IPlayerManager/ExistsEmailOrNicknameResponse")]
        bool ExistsEmailOrNickname(string nickname, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/ExistsEmailOrNickname", ReplyAction="http://tempuri.org/IPlayerManager/ExistsEmailOrNicknameResponse")]
        System.Threading.Tasks.Task<bool> ExistsEmailOrNicknameAsync(string nickname, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/SendValidationEmail", ReplyAction="http://tempuri.org/IPlayerManager/SendValidationEmailResponse")]
        bool SendValidationEmail(string toEmail, string affair, int validationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/SendValidationEmail", ReplyAction="http://tempuri.org/IPlayerManager/SendValidationEmailResponse")]
        System.Threading.Tasks.Task<bool> SendValidationEmailAsync(string toEmail, string affair, int validationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/UpdatePassword", ReplyAction="http://tempuri.org/IPlayerManager/UpdatePasswordResponse")]
        bool UpdatePassword(string password, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/UpdatePassword", ReplyAction="http://tempuri.org/IPlayerManager/UpdatePasswordResponse")]
        System.Threading.Tasks.Task<bool> UpdatePasswordAsync(string password, string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlayerManagerChannel : NoThanks.NoThanksService.IPlayerManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlayerManagerClient : System.ServiceModel.ClientBase<NoThanks.NoThanksService.IPlayerManager>, NoThanks.NoThanksService.IPlayerManager {
        
        public PlayerManagerClient() {
        }
        
        public PlayerManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlayerManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NoThanks.NoThanksService.Player Login(string nickname, string password) {
            return base.Channel.Login(nickname, password);
        }
        
        public System.Threading.Tasks.Task<NoThanks.NoThanksService.Player> LoginAsync(string nickname, string password) {
            return base.Channel.LoginAsync(nickname, password);
        }
        
        public bool Register(NoThanks.NoThanksService.Player player) {
            return base.Channel.Register(player);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterAsync(NoThanks.NoThanksService.Player player) {
            return base.Channel.RegisterAsync(player);
        }
        
        public int GenerateCode() {
            return base.Channel.GenerateCode();
        }
        
        public System.Threading.Tasks.Task<int> GenerateCodeAsync() {
            return base.Channel.GenerateCodeAsync();
        }
        
        public bool ExistsEmailOrNickname(string nickname, string email) {
            return base.Channel.ExistsEmailOrNickname(nickname, email);
        }
        
        public System.Threading.Tasks.Task<bool> ExistsEmailOrNicknameAsync(string nickname, string email) {
            return base.Channel.ExistsEmailOrNicknameAsync(nickname, email);
        }
        
        public bool SendValidationEmail(string toEmail, string affair, int validationCode) {
            return base.Channel.SendValidationEmail(toEmail, affair, validationCode);
        }
        
        public System.Threading.Tasks.Task<bool> SendValidationEmailAsync(string toEmail, string affair, int validationCode) {
            return base.Channel.SendValidationEmailAsync(toEmail, affair, validationCode);
        }
        
        public bool UpdatePassword(string password, string email) {
            return base.Channel.UpdatePassword(password, email);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatePasswordAsync(string password, string email) {
            return base.Channel.UpdatePasswordAsync(password, email);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NoThanksService.IGameService", CallbackContract=typeof(NoThanks.NoThanksService.IGameServiceCallback))]
    public interface IGameService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/NewRoom", ReplyAction="http://tempuri.org/IGameService/NewRoomResponse")]
        bool NewRoom(string hostUsername, string roomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/NewRoom", ReplyAction="http://tempuri.org/IGameService/NewRoomResponse")]
        System.Threading.Tasks.Task<bool> NewRoomAsync(string hostUsername, string roomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/GenerateRoomCode", ReplyAction="http://tempuri.org/IGameService/GenerateRoomCodeResponse")]
        string GenerateRoomCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/GenerateRoomCode", ReplyAction="http://tempuri.org/IGameService/GenerateRoomCodeResponse")]
        System.Threading.Tasks.Task<string> GenerateRoomCodeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/CheckQuota", ReplyAction="http://tempuri.org/IGameService/CheckQuotaResponse")]
        bool CheckQuota(string roomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/CheckQuota", ReplyAction="http://tempuri.org/IGameService/CheckQuotaResponse")]
        System.Threading.Tasks.Task<bool> CheckQuotaAsync(string roomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/RecoverRoomPlayers", ReplyAction="http://tempuri.org/IGameService/RecoverRoomPlayersResponse")]
        NoThanks.NoThanksService.Player[] RecoverRoomPlayers(string roomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/RecoverRoomPlayers", ReplyAction="http://tempuri.org/IGameService/RecoverRoomPlayersResponse")]
        System.Threading.Tasks.Task<NoThanks.NoThanksService.Player[]> RecoverRoomPlayersAsync(string roomId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/StartGame")]
        void StartGame(string roomId, string[] message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/StartGame")]
        System.Threading.Tasks.Task StartGameAsync(string roomId, string[] message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/Connect", ReplyAction="http://tempuri.org/IGameService/ConnectResponse")]
        void Connect(string username, string roomId, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/Connect", ReplyAction="http://tempuri.org/IGameService/ConnectResponse")]
        System.Threading.Tasks.Task ConnectAsync(string username, string roomId, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/Disconnect", ReplyAction="http://tempuri.org/IGameService/DisconnectResponse")]
        void Disconnect(string username, string roomId, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/Disconnect", ReplyAction="http://tempuri.org/IGameService/DisconnectResponse")]
        System.Threading.Tasks.Task DisconnectAsync(string username, string roomId, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/ExpelPlayer", ReplyAction="http://tempuri.org/IGameService/ExpelPlayerResponse")]
        void ExpelPlayer(string username, string roomId, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/ExpelPlayer", ReplyAction="http://tempuri.org/IGameService/ExpelPlayerResponse")]
        System.Threading.Tasks.Task ExpelPlayerAsync(string username, string roomId, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/SendMessage")]
        void SendMessage(string message, string username, string roomId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/SendMessage")]
        System.Threading.Tasks.Task SendMessageAsync(string message, string username, string roomId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/SendWhisper")]
        void SendWhisper(string receiver, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/SendWhisper")]
        System.Threading.Tasks.Task SendWhisperAsync(string receiver, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/CreateDeck")]
        void CreateDeck(string roomId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/CreateDeck")]
        System.Threading.Tasks.Task CreateDeckAsync(string roomId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/TakeCard")]
        void TakeCard(string roomId, string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/TakeCard")]
        System.Threading.Tasks.Task TakeCardAsync(string roomId, string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/SkipPlayersTurn")]
        void SkipPlayersTurn(string roomId, string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/SkipPlayersTurn")]
        System.Threading.Tasks.Task SkipPlayersTurnAsync(string roomId, string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/FinishGame")]
        void FinishGame(string roomId, NoThanks.NoThanksService.Player[] players);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/FinishGame")]
        System.Threading.Tasks.Task FinishGameAsync(string roomId, NoThanks.NoThanksService.Player[] players);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/MessageCallBack")]
        void MessageCallBack(string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/WhisperCallBack")]
        void WhisperCallBack(string sender, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/StartGameRoom")]
        void StartGameRoom(NoThanks.NoThanksService.RoomStatus roomStatus, NoThanks.NoThanksService.Player[] players);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/PlayerExpeled")]
        void PlayerExpeled(string nickname, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/SkipPlayersTurnCallback")]
        void SkipPlayersTurnCallback(int round, int roomTokens);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/NextTurn")]
        void NextTurn(int round, NoThanks.NoThanksService.Player[] roomPlayers);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/UpdateDeck")]
        void UpdateDeck(NoThanks.NoThanksService.CardType[] gameDeck, int roomTokens);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/EndGame")]
        void EndGame(NoThanks.NoThanksService.RoomStatus roomStatus);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameServiceChannel : NoThanks.NoThanksService.IGameService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameServiceClient : System.ServiceModel.DuplexClientBase<NoThanks.NoThanksService.IGameService>, NoThanks.NoThanksService.IGameService {
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool NewRoom(string hostUsername, string roomId) {
            return base.Channel.NewRoom(hostUsername, roomId);
        }
        
        public System.Threading.Tasks.Task<bool> NewRoomAsync(string hostUsername, string roomId) {
            return base.Channel.NewRoomAsync(hostUsername, roomId);
        }
        
        public string GenerateRoomCode() {
            return base.Channel.GenerateRoomCode();
        }
        
        public System.Threading.Tasks.Task<string> GenerateRoomCodeAsync() {
            return base.Channel.GenerateRoomCodeAsync();
        }
        
        public bool CheckQuota(string roomId) {
            return base.Channel.CheckQuota(roomId);
        }
        
        public System.Threading.Tasks.Task<bool> CheckQuotaAsync(string roomId) {
            return base.Channel.CheckQuotaAsync(roomId);
        }
        
        public NoThanks.NoThanksService.Player[] RecoverRoomPlayers(string roomId) {
            return base.Channel.RecoverRoomPlayers(roomId);
        }
        
        public System.Threading.Tasks.Task<NoThanks.NoThanksService.Player[]> RecoverRoomPlayersAsync(string roomId) {
            return base.Channel.RecoverRoomPlayersAsync(roomId);
        }
        
        public void StartGame(string roomId, string[] message) {
            base.Channel.StartGame(roomId, message);
        }
        
        public System.Threading.Tasks.Task StartGameAsync(string roomId, string[] message) {
            return base.Channel.StartGameAsync(roomId, message);
        }
        
        public void Connect(string username, string roomId, string message) {
            base.Channel.Connect(username, roomId, message);
        }
        
        public System.Threading.Tasks.Task ConnectAsync(string username, string roomId, string message) {
            return base.Channel.ConnectAsync(username, roomId, message);
        }
        
        public void Disconnect(string username, string roomId, string message) {
            base.Channel.Disconnect(username, roomId, message);
        }
        
        public System.Threading.Tasks.Task DisconnectAsync(string username, string roomId, string message) {
            return base.Channel.DisconnectAsync(username, roomId, message);
        }
        
        public void ExpelPlayer(string username, string roomId, string message) {
            base.Channel.ExpelPlayer(username, roomId, message);
        }
        
        public System.Threading.Tasks.Task ExpelPlayerAsync(string username, string roomId, string message) {
            return base.Channel.ExpelPlayerAsync(username, roomId, message);
        }
        
        public void SendMessage(string message, string username, string roomId) {
            base.Channel.SendMessage(message, username, roomId);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(string message, string username, string roomId) {
            return base.Channel.SendMessageAsync(message, username, roomId);
        }
        
        public void SendWhisper(string receiver, string message) {
            base.Channel.SendWhisper(receiver, message);
        }
        
        public System.Threading.Tasks.Task SendWhisperAsync(string receiver, string message) {
            return base.Channel.SendWhisperAsync(receiver, message);
        }
        
        public void CreateDeck(string roomId) {
            base.Channel.CreateDeck(roomId);
        }
        
        public System.Threading.Tasks.Task CreateDeckAsync(string roomId) {
            return base.Channel.CreateDeckAsync(roomId);
        }
        
        public void TakeCard(string roomId, string username) {
            base.Channel.TakeCard(roomId, username);
        }
        
        public System.Threading.Tasks.Task TakeCardAsync(string roomId, string username) {
            return base.Channel.TakeCardAsync(roomId, username);
        }
        
        public void SkipPlayersTurn(string roomId, string username) {
            base.Channel.SkipPlayersTurn(roomId, username);
        }
        
        public System.Threading.Tasks.Task SkipPlayersTurnAsync(string roomId, string username) {
            return base.Channel.SkipPlayersTurnAsync(roomId, username);
        }
        
        public void FinishGame(string roomId, NoThanks.NoThanksService.Player[] players) {
            base.Channel.FinishGame(roomId, players);
        }
        
        public System.Threading.Tasks.Task FinishGameAsync(string roomId, NoThanks.NoThanksService.Player[] players) {
            return base.Channel.FinishGameAsync(roomId, players);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NoThanksService.IUpdateProfile")]
    public interface IUpdateProfile {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateProfile/SaveImage", ReplyAction="http://tempuri.org/IUpdateProfile/SaveImageResponse")]
        bool SaveImage(string imageManager, int idProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateProfile/SaveImage", ReplyAction="http://tempuri.org/IUpdateProfile/SaveImageResponse")]
        System.Threading.Tasks.Task<bool> SaveImageAsync(string imageManager, int idProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateProfile/GetGlobalPlayers", ReplyAction="http://tempuri.org/IUpdateProfile/GetGlobalPlayersResponse")]
        string[] GetGlobalPlayers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateProfile/GetGlobalPlayers", ReplyAction="http://tempuri.org/IUpdateProfile/GetGlobalPlayersResponse")]
        System.Threading.Tasks.Task<string[]> GetGlobalPlayersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateProfile/UpdateNewNickname", ReplyAction="http://tempuri.org/IUpdateProfile/UpdateNewNicknameResponse")]
        bool UpdateNewNickname(string nickname, string newNickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateProfile/UpdateNewNickname", ReplyAction="http://tempuri.org/IUpdateProfile/UpdateNewNicknameResponse")]
        System.Threading.Tasks.Task<bool> UpdateNewNicknameAsync(string nickname, string newNickname);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUpdateProfileChannel : NoThanks.NoThanksService.IUpdateProfile, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateProfileClient : System.ServiceModel.ClientBase<NoThanks.NoThanksService.IUpdateProfile>, NoThanks.NoThanksService.IUpdateProfile {
        
        public UpdateProfileClient() {
        }
        
        public UpdateProfileClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UpdateProfileClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateProfileClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateProfileClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SaveImage(string imageManager, int idProfile) {
            return base.Channel.SaveImage(imageManager, idProfile);
        }
        
        public System.Threading.Tasks.Task<bool> SaveImageAsync(string imageManager, int idProfile) {
            return base.Channel.SaveImageAsync(imageManager, idProfile);
        }
        
        public string[] GetGlobalPlayers() {
            return base.Channel.GetGlobalPlayers();
        }
        
        public System.Threading.Tasks.Task<string[]> GetGlobalPlayersAsync() {
            return base.Channel.GetGlobalPlayersAsync();
        }
        
        public bool UpdateNewNickname(string nickname, string newNickname) {
            return base.Channel.UpdateNewNickname(nickname, newNickname);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateNewNicknameAsync(string nickname, string newNickname) {
            return base.Channel.UpdateNewNicknameAsync(nickname, newNickname);
        }
    }
}
