//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class MatchsHistory
    {
        public int idMatch { get; set; }
        public Nullable<int> point { get; set; }
        public string result { get; set; }
        public Nullable<int> idGame { get; set; }
        public Nullable<int> idPlayer { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
    }
}
